apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment # deployment name
  labels:
    app: mongo
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env: # not secured way
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo # should match containerPort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # should match containerPort