apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - name: hw-depl-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  ports:
  - nodePort: 31003
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    # run: load-balancer-example-000 # FAIL
    run: load-balancer-example
  type: NodePort
