apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # deployment name
  labels:
    app: nginx
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80 # should match containerPort
      nodePort: 31144